<?php 

class InstantSurah
{
	/* variabel */	
		var $al_fatihah;
		var $al_baqarah;
		var $ali_imran;
		var $an_nisa;
		var $al_maidah;
		var $al_anam; 
		var $al_araf; 
		var $al_anfal;
		var $at_taubah;
		var $yunus;
		var $hud;
		var $yusuf;
		var $ar_rad; 
		var $ibrahim;
		var $al_hijr;
		var $an_nahl;
		var $al_isra;
		var $al_kahfi;
		var $maryam;
		var $thaha;
		var $al_anbiya;
		var $al_hajj;
		var $al_muminun; 
		var $an_nur;
		var $al_furqan;
		var $asy_syuara; 
		var $an_naml;
		var $al_qashash;
		var $al_ankabut;
		var $ar_rum;
		var $luqman;
		var $as_sajdah;
		var $al_ahzab;
		var $saba;
		var $fathir;
		var $yasin;
		var $ash_shaffat;
		var $shad;
		var $az_zumar;
		var $ghafir;
		var $fushshilat;
		var $asy_syura;
		var $az_zukhruf;
		var $ad_dukhan;
		var $al_jatsiyah;
		var $al_ahqaf;
		var $muhammad;
		var $al_fath;
		var $al_hujurat;
		var $qaf;
		var $adz_dzariyat;
		var $ath_thur;
		var $an_najm;
		var $al_qamar;
		var $ar_rahman;
		var $al_waqiah; 
		var $al_hadid;
		var $al_mujadilah;
		var $al_hasyr;
		var $al_mumtahanah;
		var $ash_shaf;
		var $al_jumuah; 
		var $al_munafiqun;
		var $at_taghabun;
		var $ath_thalaq;
		var $at_tahrim;
		var $al_mulk;
		var $al_qalam;
		var $al_haqqah;
		var $al_maarij; 
		var $nuh;
		var $al_jinn;
		var $al_muzzammil;
		var $al_muddatstsir;
		var $al_qiyamah;
		var $al_insan;
		var $al_mursalat;
		var $an_naba;
		var $an_naziat; 
		var $abasa;
		var $at_takwir;
		var $al_infithar;
		var $al_muthaffifin;
		var $al_insyiqaq;
		var $al_buruj;
		var $ath_thariq;
		var $al_ala; 
		var $al_ghasyiyah;
		var $al_fajr;
		var $al_balad;
		var $asy_syams;
		var $al_lail;
		var $adh_dhuha;
		var $al_insyirah;
		var $at_tin;
		var $al_alaq;
		var $al_qadr;
		var $al_bayyinah;
		var $az_zalzalah;
		var $al_adiyat;
		var $al_qariah; 
		var $at_takatsur;
		var $al_ashr;
		var $al_humazah;
		var $al_fil;
		var $al_quraisy;
		var $al_maun; 
		var $al_kautsar;
		var $al_kafirun;
		var $an_nashr;
		var $al_lahab;
		var $al_ikhlas;
		var $al_falaq;
		var $an_nas;
		var $belum_ada;

	function __construct()
	{
		$this->al_fatihah = new Surah("Al-Fatihah", 7);
		$this->al_baqarah = new Surah("Al-Baqarah", 286);
		$this->ali_imran = new Surah("Ali-Imran", 200);
		$this->an_nisa = new Surah("An-Nisa", 176);
		$this->al_maidah = new Surah("Al-Maidah", 120);
		$this->al_anam = new Surah("Al-An'am", 165);
		$this->al_araf = new Surah("Al-A'raf", 206);
		$this->al_anfal = new Surah("Al-Anfal", 75);
		$this->at_taubah = new Surah("At-Taubah", 129);
		$this->yunus = new Surah("Yunus", 109);
		$this->hud = new Surah("Hud", 123);
		$this->yusuf = new Surah("Yusuf", 111);
		$this->ar_rad = new Surah("Ar-Ra'd", 43);
		$this->ibrahim = new Surah("Ibrahim", 52);
		$this->al_hijr = new Surah("Al-Hijr", 99);
		$this->an_nahl = new Surah("Al-Nahl", 128);
		$this->al_isra = new Surah("Al-Isra", 111);
		$this->al_kahfi = new Surah("Al-Kahfi", 110);
		$this->maryam = new Surah("Maryam", 98);
		$this->thaha = new Surah("Thaha", 135);
		$this->al_anbiya = new Surah("Al-Anbiya'", 112);
		$this->al_hajj = new Surah("Al-Hajj", 78);
		$this->al_muminun = new Surah("Al-Mu`minun", 118);
		$this->an_nur = new Surah("An-Nur", 64);
		$this->al_furqan = new Surah("Al-Furqan", 77);
		$this->asy_syuara = new Surah("Asy-Syu'ara", 227);
		$this->an_naml = new Surah("An-Naml", 93);
		$this->al_qashash = new Surah("Al-Qashash", 88);
		$this->al_ankabut = new Surah("Al-Ankabut", 69);
		$this->ar_rum = new Surah("Ar-Rum", 60);
		$this->luqman = new Surah("Luqman", 34);
		$this->as_sajdah = new Surah("As-Sajdah", 30);
		$this->al_ahzab = new Surah("Al-Ahzab", 73);
		$this->saba = new Surah("Saba", 54);
		$this->fathir = new Surah("Fathir", 45);
		$this->yasin = new Surah("Yasin", 83);
		$this->ash_shaffat = new Surah("Ash-Shaffat", 182);
		$this->shad = new Surah("Shad", 88);
		$this->az_zumar = new Surah("Az-Zumar", 75);
		$this->ghafir = new Surah("Ghafir", 85);
		$this->fushshilat = new Surah("Fushshilat", 54);
		$this->asy_syura = new Surah("Asy-Syura", 53);
		$this->az_zukhruf = new Surah("Az-Zukhruf", 89);
		$this->ad_dukhan = new Surah("Ad-Dukhan", 59);
		$this->al_jatsiyah = new Surah("Al-Jatsiyah", 37);
		$this->al_ahqaf = new Surah("Al-Ahqaf", 35);
		$this->muhammad = new Surah("Muhammad", 38);
		$this->al_fath = new Surah("Al-Fath", 29);
		$this->al_hujurat = new Surah("Al-Hujurat", 18);
		$this->qaf = new Surah("Qaf", 45);
		$this->adz_dzariyat = new Surah("Adz-Dzariyat", 60);
		$this->ath_thur = new Surah("Ath-Thur", 49);
		$this->an_najm = new Surah("An-Najm", 62);
		$this->al_qamar = new Surah("Al-Qamar", 55);
		$this->ar_rahman = new Surah("Ar-Rahman", 78);
		$this->al_waqiah = new Surah("Al-Waqi'ah", 96);
		$this->al_hadid = new Surah("Al-Hadid", 29);
		$this->al_mujadilah = new Surah("Al-Mujadilah", 22);
		$this->al_hasyr = new Surah("Al-Hasyr", 24);
		$this->al_mumtahanah = new Surah("Al-Mumtahanah", 13);
		$this->ash_shaf = new Surah("Ash-Shaf", 14);
		$this->al_jumuah = new Surah("Al-Jumu'ah", 11);
		$this->al_munafiqun = new Surah("Al-Munafiqun", 11);
		$this->at_taghabun = new Surah("At-Taghabun", 18);
		$this->ath_thalaq = new Surah("Ath-Thalaq", 12);
		$this->at_tahrim = new Surah("At-Tahrim", 12);
		$this->al_mulk = new Surah("Al-Mulk", 30);
		$this->al_qalam = new Surah("Al-Qalam", 52);
		$this->al_haqqah = new Surah("Al-Haqqah", 52);
		$this->al_maarij = new Surah("Al-Ma'arij", 44);
		$this->nuh = new Surah("Nuh", 28);
		$this->al_jinn = new Surah("Al-Jinn", 28);
		$this->al_muzzammil = new Surah("Al-Muzzammil", 20);
		$this->al_muddatstsir = new Surah("Al-Muddatstsir", 56);
		$this->al_qiyamah = new Surah("Al-Qiyamah", 40);
		$this->al_insan = new Surah("Al-Insan", 31);
		$this->al_mursalat = new Surah("Al-Mursalat", 50);
		$this->an_naba = new Surah("An-Naba`", 40);
		$this->an_naziat = new Surah("An-Nazi'at", 46);
		$this->abasa = new Surah("'Abasa", 42);
		$this->at_takwir = new Surah("At-Takwir", 29);
		$this->al_infithar = new Surah("Al-Infithar", 19);
		$this->al_muthaffifin = new Surah("Al-Muthaffifin", 36);
		$this->al_insyiqaq = new Surah("Al-Insyiqaq", 25);
		$this->al_buruj = new Surah("Al-Buruj", 22);
		$this->ath_thariq = new Surah("Ath-Thariq", 17);
		$this->al_ala = new Surah("Al-A'la", 19);
		$this->al_ghasyiyah = new Surah("Al-Ghasyiyah", 26);
		$this->al_fajr = new Surah("Al-Fajr", 30);
		$this->al_balad = new Surah("Al-Balad", 20);
		$this->asy_syams = new Surah("Asy-Syams", 15);
		$this->al_lail = new Surah("Al-Lail", 21);
		$this->adh_dhuha = new Surah("Adh-Dhuha", 11);
		$this->al_insyirah = new Surah("Al-Insyirah", 8);
		$this->at_tin = new Surah("At-Tin", 8);
		$this->al_alaq = new Surah("Al-'Alaq", 19);
		$this->al_qadr = new Surah("Al-Qadr", 5);
		$this->al_bayyinah = new Surah("Al-Bayyinah", 8);
		$this->az_zalzalah = new Surah("Az-Zalzalah", 8);
		$this->al_adiyat = new Surah("Al-'Adiyat", 11);
		$this->al_qariah = new Surah("Al-Qari'ah", 11);
		$this->at_takatsur = new Surah("At-Takatsur", 8);
		$this->al_ashr = new Surah("Al-'Ashr", 3);
		$this->al_humazah = new Surah("Al-Humazah", 9);
		$this->al_fil = new Surah("Al-Fil", 5);
		$this->al_quraisy = new Surah("Al-Quraisy", 4);
		$this->al_maun = new Surah("Al-Ma'un", 7);
		$this->al_kautsar = new Surah("Al-Kautsar", 3);
		$this->al_kafirun = new Surah("Al-Kafirun", 6);
		$this->an_nashr = new Surah("An-Nashr", 3);
		$this->al_lahab = new Surah("Al-Lahab", 5);
		$this->al_ikhlas = new Surah("Al-Ikhlas", 4);
		$this->al_falaq = new Surah("Al-Falaq", 5);
		$this->an_nas = new Surah("An-Nas", 6);
		$this->belum_ada = new Surah("Belum ada", 0);
	}

	function getSurah($s)
	{
		return $this->$s;
	}
}
